trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - '*.yml'
      - '*.json'
      - .gitignore
      - .npmignore
      - README.md

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'
- script: |
    npm install -g aws-cdk
    npm install
    npm run build
    cdk synth
- task: AWSShellScript@1
  inputs:
    awsCredentials: 'AWS'
    regionName: '$(AWS_REGION)'
    scriptType: 'inline'
    inlineScript: |
      cdk deploy